### PR TITLE
Add missing statement to Makefile

### PR DESCRIPTION
**Pull request by rtkmhart**
Starting on a fresh VM, I needed to add this line to the Makefile to get gostatsd to build properly.

### CODE REVIEW

**Comment by ash2k** [comment]
What commands you are executing and what output you are getting? This should not be required because dependency on `logrus` in declared in `glide.yaml` and `glide install` invoked from `make setup` should pull it into `vendor` directory.

**Comment by rtkmhart** [comment]
It was a "make setup" that failed, on a freshly provisioned Ubuntu 12.04 LTS VM with go version 1.6.2. It's quite possible I messed something up.

**Comment by ash2k** [comment]
Could you provide a full output? It works in Travis builds so... I'm not sure what is wrong.

**Comment by ash2k** [comment]
Please reopen with more information if it is still relevant.

**Pull request closed without merging**
