### PR TITLE
Fix vgo build

### PR DESCRIPTION
**Pull request by linxGnu**
Currently, `github.com/jbenet/go-reuseport` is now deprecated and redirect to `github.com/libp2p/go-reuseport`. 

This small fix tried to use `github.com/libp2p/go-reuseport` directly in `statsd.go` to avoid vgo confusing. 

It also adds `go.mod` for vgo compatible.

### CODE REVIEW

**Comment by linxGnu** [comment]
Kindly ping @tiedotguy 
Could you please take a look for this quick fix. One of our project using vgo has this trouble.

**Comment by tiedotguy** [comment]
Hi

I'm double-checking if we need the CLA signed for a change like this.  Can you please sign it (either individual or corporate depending on your situation), to speed the process up if it turns out we do need it?

Details are at https://github.com/atlassian/gostatsd#contributors

If it turns out we don't, I should be able to merge this tomorrow.

**Comment by linxGnu** [comment]
@tiedotguy thank you for your review. I have signed the CLA with email: `linhduonggnu@gmail.com`

Please check it again. Thank you

**Comment by tiedotguy** [comment]
All good!

**Pull request merged**
