### PR TITLE
upgrade alpine 3.14.3 -> 3.15.0

### PR DESCRIPTION
**Pull request by jamesmoessis**
fixes a bunch of busybox vulnerabilities

### CODE REVIEW

**Comment by tiedotguy** [comment]
lgtm, but give it a changelog.md update, I guess a patch bump is fine for this.

**Review by tiedotguy — CHANGES_REQUESTED** [review]
Needs a changelog update

**Comment by jamesmoessis** [comment]
@tiedotguy oh I didn't release there was unreleased changes in master. Yikes, might just wait for @MovieStoreGuy to be back then

**Comment by MovieStoreGuy** [comment]
@jamesmoessis ,

Could you update the dependabot settings to bump the docker images used as well in here?

**Review by MovieStoreGuy — APPROVED** [review]

**Review by tiedotguy — APPROVED** [review]

**Comment by MovieStoreGuy** [comment]
@jamesmoessis , feel free to follow up in a future PR.

**Pull request merged**
