### PR TITLE
Update readme to reference contributor license agreement

### PR DESCRIPTION
**Pull request by aelse**
Atlassian has an internal process for managing its open source projects. This PR adds the CLA to gostatsd.

@kisielk, I'm a developer working with @ash2k (though I've mainly been lurking until now). Would you be willing to accept this agreement to cover your past contributions to gostatsd?

Please note that signing this agreement doesn't change your ownership of any code you wrote or how you are credited in the project documentation, it just grants some protections our lawyers tell us we need to manage this kind of project. It can be done entirely online at https://na2.docusign.net/Member/PowerFormSigning.aspx?PowerFormId=3f94fbdc-2fbe-46ac-b14c-5d152700ae5d

### CODE REVIEW

**Comment by kisielk** [comment]
Fine by me.

**Comment by aelse** [comment]
Thanks @kisielk, that's great.

**Comment by kisielk** [comment]
@aelse I signed the agreement

**Comment by aelse** [comment]
@kisielk Thanks for doing that, it makes things easy for me. And thanks for your work on this project :)

@ash2k Please merge in.

**Pull request merged**
