### PR TITLE
rewrite rule for golang.org/x/net/http2

### PR DESCRIPTION
**Pull request by alvarocabanas**
Add rewrite rule for golang.org/x/net/http2 to fix vulnerability fixed on version 0.23.0.

### CODE REVIEW

**Comment by alvarocabanas** [comment]
Hi @MovieStoreGuy, do you think this could be merged? Is just bumping a dependency that Snyk is marking having a vulnerability:

✗ High severity vulnerability found in golang.org/x/net/http2
  Description: Allocation of Resources Without Limits or Throttling
  Info: https://security.snyk.io/vuln/SNYK-GOLANG-GOLANGORGXNETHTTP2-6531285
  Introduced through: golang.org/x/net/http2@v0.17.0
  From: golang.org/x/net/http2@v0.17.0
  Fixed in: 0.23.0

**Comment by MovieStoreGuy** [comment]
Hey @alvarocabanas ,

Of course it can, I am just not great with github notifications. I'll need you to fix up the conflicts and this can be merged.

**Comment by alvarocabanas** [comment]
> Hey @alvarocabanas ,
> 
> Of course it can, I am just not great with github notifications. I'll need you to fix up the conflicts and this can be merged.

Thanks @MovieStoreGuy, I have just rebased my branch and fixed the conflicts and is ready to be merged.

**Comment by MovieStoreGuy** [comment]
I will leave this for dependabot to address.

**Pull request closed without merging**
